name: 'comp4050-db'
version: '3'
services:
  postgres:
    container_name: "pgsql-dev"
    image: postgres:16.4
    volumes:
      - ./viva-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: 'postgres'
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_PASSWORD=default